version: "3.8"

services:
  server:
    container_name: server
    build:
      context: ../../
      dockerfile: ops/docker/go/Dockerfile
    working_dir: /app
    volumes:
      - ../../src:/app/src
    ports:
      - 8080:8080
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
    networks:
      default:
        aliases:
          - 31ngo-server.local
    links:
      - mongodb
    depends_on:
      - mongodb

  mongodb:
    container_name: db
    image: mongo:4.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017
